/* Basira seal «ختم المعارضة» — inline SVG (no request, no CLS).
 * Geometry is generated by docs/design/brand/seal.py (single source of truth; `--check` guards the
 * 8-fold khatam: 8 tips every 45°, never a hexagram). Do not hand-edit the paths below — regenerate.
 *   khatam  two squares, half-side 7.6, one rotated 45°
 *   dāra    window r = 5 cut through (even-odd) — Ibn al-Ṣalāḥ: the circle between hadiths, dotted once collated
 *   nuqta   gold rhombus, half-diagonal 2.6 — Ibn Muqla's proportional unit
 * Rationale and measurements: docs/design/README.md §1. */
import * as React from 'react';

const STAR = "M12.000 1.252 L15.148 4.400 L19.600 4.400 L19.600 8.852 L22.748 12.000 L19.600 15.148 L19.600 19.600 L15.148 19.600 L12.000 22.748 L8.852 19.600 L4.400 19.600 L4.400 15.148 L1.252 12.000 L4.400 8.852 L4.400 4.400 L8.852 4.400Z M7 12a5 5 0 1 0 10 0a5 5 0 1 0 -10 0Z";
const NUQTA = "M12 9.4 14.6 12 12 14.6 9.4 12Z";

export interface LogoMarkProps extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
  /** 'ink' = night seal + gold dot (light surfaces); 'paper' = light seal + light-gold dot (dark surfaces);
   *  'tile' = app-icon tile; 'mono' = currentColor. Default follows the theme via CSS vars. */
  variant?: 'auto' | 'ink' | 'paper' | 'tile' | 'mono';
  title?: string;
}

export function LogoMark({ size = 40, variant = 'auto', title = 'بصيرة — Basira', ...rest }: LogoMarkProps) {
  const seal = variant === 'mono' ? 'currentColor' : variant === 'ink' ? '#12183F' : variant === 'paper' || variant === 'tile' ? '#F6F2E9' : 'var(--seal-ink)';
  const dot = variant === 'mono' ? 'currentColor' : variant === 'ink' ? '#B8893A' : variant === 'paper' || variant === 'tile' ? '#D9B66E' : 'var(--seal-dot)';
  return (
    // An empty `title` makes the mark decorative (aria-hidden) so a parent link's wordmark stays its name.
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      className="seal"
      {...(title ? { role: 'img', 'aria-label': title } : { 'aria-hidden': true, focusable: false })}
      {...rest}
    >
      {title ? <title>{title}</title> : null}
      {variant === 'tile' && <rect width="24" height="24" rx="5.3" fill="#0B0F2E" />}
      <g transform={variant === 'tile' ? 'translate(3.84 3.84) scale(.68)' : undefined}>
        <path d={STAR} fill={seal} fillRule="evenodd" />
        <path d={NUQTA} fill={dot} />
      </g>
    </svg>
  );
}

/** Horizontal lockup: seal + Kufic wordmark. Text, not an image, so it inherits colour and stays crisp. */
export function LogoHorizontal({ height = 40, lang = 'ar' }: { height?: number; lang?: 'ar' | 'en' }) {
  return (
    <span className="seal-lockup" style={{ gap: height * 0.32 }}>
      <LogoMark size={height} title="" />
      <b style={{ fontSize: height * 0.78 }}>{lang === 'ar' ? 'بصيرة' : 'Basira'}</b>
    </span>
  );
}

export default LogoMark;
